#Marcin Paweloszek -- PSI II semestr
# Wersja docker-compose
version: '2'
# Uruchamiane usługi
services:
        # Wordpress wraz z serwerem
        wordpress:
                image: wordpress:4.5
                container_name: wordpress-container
                depends_on:
                        - db
                links:
                        - db:mysql
                ports:
                        - 80:80
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_PASSWORD: wordpress
                        WORDPRESS_DB_USER: wordpress
                networks:
                        marcinPawl:
                restart: always
        # Baza danych z którą łączy się Wordpress
        db:
                image: mariadb:10.1
                container_name: mariadb-server
                volumes_from:
                        - db-data
                environment:
                        MYSQL_ROOT_PASSWORD: example
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress
                networks:
                        marcinPawl:
                restart: always
        # Storage do przechowywania danych z bazy
        db-data:
                image: mariadb:10.1
                container_name: db_storage
                volumes:
                        - ./mariadb:/var/lib/mysql
                networks:
                        marcinPawl:
                command: "true"
        # Phpmyadmin do zarządzania bazą danych
        phpmyadmin:
                image: phpmyadmin/phpmyadmin
                container_name: phpmyadmin-container
                ports:
                        - 81:80
                links:
                        - db
                networks:
                        marcinPawl:
                environment:
                        PMA_HOST: db
# Konfiguracja sieci
networks:
   marcinPawl:
      driver: bridge
  
